### ISSUE TITLE
Feature Request: Auto Increment package.json

### ISSUE THREAD

**Issue by veenarm** [hyper-expanse/semantic-delivery-gitlab#28]
Title is self explanatory, any chance we can get a feature/option to auto update the `package.json` version, to match what the cli detects the next version to be? do this commit then release that commit as the tagged copy? 

So we increment then tag?

**Comment by hutson** [comment]
> Title is self explanatory, any chance we can get a feature/option to auto update the package.json version, to match what the cli detects the next version to be? do this commit then release that commit as the tagged copy?

When I first wrote this package, I was actually looking to migrate away from another tool that did just that; incremented the `version` field in `package.json` and pushed the change to the repository. Since I publish a new version on every releasable change, it led to nearly every other commit being nothing more than a version change to `package.json`.

However, if you are interested in that feature, the tool I originally used was called [`release-it`](https://www.npmjs.com/package/release-it#git). It requires you to specify the version you want to bump (patch, minor, or major). 

If you would like to keep the automated version detection of this package, but still commit the version to your repository, may I suggest using the `semantic-release` package with the [`@semantic-release/git`](https://www.npmjs.com/package/@semantic-release/git) plugin. This package was originally modeled on `semantic-release`, with added support for GitLab and the removal the step to push changes to a remote Git repository.

After all that, if you still like this particular package, please consider forking this repository and publishing a new package (perhaps under your own namespace), that incorporates a step to run `git commit -a -m && git push` for your specific use case.

**Comment by veenarm** [comment]
Yeah, I'm using release-it and another tool to use the angular commit conventions now.
Shouldn't you bump the versions though if you're making changes? we're only having this run in the default/primary branch in the release train.

I can see it getting annoying if you keep committing directly to the main branch though. :)

**Comment by hutson** [comment]
> Shouldn't you bump the versions though if you're making changes?

For my projects, yes, I used to run `semantic-delivery-gitlab` to automatically create the appropriate tag based on all commits since the last release. The tag would point to the last commit. Since I never modify `package.json`, the version in `package.json` for that tagged commit would essentially be a [placeholder version](https://github.com/hyper-expanse/semantic-delivery-gitlab/blob/406aa1221ccec9b5e820d200285c32266ee407cf/package.json#L68). 

To publish the code at the newly created tag, I use [`npm-deploy-git-tag`](https://github.com/hyper-expanse/npm-deploy-git-tag#hutsonnpm-deploy-git-tag). `npm-deploy-git-tag` will modify the `package.json` file locally to set the `version` field to match the current tag, and then call `npm publish`.

As a result of this workflow, I never commit updates to the `version` field, but I am able to publish the tagged version to the npm registry.

I'll eventually get back around to writing a `semantic-delivery-github` tool for GitHub.

**Comment by hutson** [comment]
@veenarm here's the GitLab configuration I used for my release workflow - https://github.com/hyper-expanse/semantic-delivery-gitlab/commit/1a0dd36f60c9287ec4b6266638e7635553a978e8
